#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jniloader
Version  : 1.1
Release  : 1
URL      : https://github.com/ibmsoe/jniloader/archive/jniloader-1.1.tar.gz
Source0  : https://github.com/ibmsoe/jniloader/archive/jniloader-1.1.tar.gz
Source1  : https://repo1.maven.org/maven2/com/github/fommil/jniloader/1.1/jniloader-1.1.jar
Source2  : https://repo1.maven.org/maven2/com/github/fommil/jniloader/1.1/jniloader-1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: mvn-jniloader-data = %{version}-%{release}

%description
jniloader
=========
Simple (for the end user) native library loader.
The static method in `JniLoader` enables developers to ship native
libraries in jar files which are extracted and loaded at runtime,
making native loading transparent for the end-user (as long as
they are on a platform supported by you).

%package data
Summary: data components for the mvn-jniloader package.
Group: Data

%description data
data components for the mvn-jniloader package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/jniloader/1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/jniloader/1.1/jniloader-1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/jniloader/1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/github/fommil/jniloader/1.1/jniloader-1.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/github/fommil/jniloader/1.1/jniloader-1.1.jar
/usr/share/java/.m2/repository/com/github/fommil/jniloader/1.1/jniloader-1.1.pom
